let 
doc = [
    Documentation.Name =  "...", 
    Documentation.FunctionName = "Sample.Function",
    Documentation.Description = "...", 
    Documentation.Examples = {
          [
            Description = "...",
            Code = functionName & "...",
            Result = "..."
          ],
          [
            Description = "...",
            Code = functionName & "...",
            Result = "..."
          ]
        }
    
  ],
  fn = (previousStep as table, ...) => 

let Source = "Copy your function here" in Source

​ in 
Value.ReplaceType(fn, Value.ReplaceMetadata(Value.Type(fn), doc))
